export const SITE = {
  website: "https://mnaoumov.github.io/",
  author: "Michael Naumov",
  profile: "https://github.com/mnaoumov",
  desc: "Programming blog by Michael Naumov",
  title: "mnaoumov.dev",
  ogImage: "og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 10,
  postPerPage: 10,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "",
    url: "",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "en",
  timezone: "America/Mexico_City",
} as const;
